repos:
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 0.5.5
    hooks:
      - id: nbqa-black
        additional_dependencies: [black==20.8b1]
      - id: nbqa-isort
        additional_dependencies: [isort==5.6.4]
      - id: nbqa-mypy
        additional_dependencies: [mypy==0.790]
        args: [--follow-imports=silent]
